apiVersionOverrides:
  ingress: "networking.k8s.io/v1"

redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  metrics:
    enabled: true
  ingress:
    enabled: true
    https: false
    #ingressClassName: traefik
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - "argo-master.127.0.0.1.nip.io" # 127.0.0.1
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2

crds:
  install: true
  keep: false